### DISCUSSION TITLE
mpf monitor doesn't show any devices

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#108] [Q&A] [answered]
Hi,

when running mpf monitor it doesn't show any devices in the device window. I see my playfield image, so  mpf monitor works somewhat.

One part of my config file is for example

```
lights:
  some_led:
    number: 0-0-1
    subtype: led
    type: rgb
```

so I would expect to see that led in my device list. Do I have to do anything else? I was not able to spot anything else I have to do in the documentation.

Thanks.
