### DISCUSSION TITLE
RGB color values like [1,2,3] not working

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#111] [Q&A] [answered]
Hello,

I am referring to this documentation

https://missionpinball.org/config/light_player/

>  Set a color to this light. Color values may be a hex string (e.g. 22FFCC), a list of RGB values (e.g. [50, 128, 206]),

The hex-values work fine, but the RGB values in [ ] I am not getting to work. I am getting this error

```
    raise ConfigFileError("Config validation error: Entry {} = \"{}\" is not valid. {}".format(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Show "attract_light_show_opt5" >> Failed to load config player attract_light_show_opt5:lights with settings {'led_strip_0_led_7': {'color': [120, 0, 0], 'fade': '500ms', 'priority': 0}, 'led_strip_0_led_6': {'color': 'AABBCC', 'fade': '500ms'}, 'led_strip_0_led_5': {'color': 'AABBCC', 'fade': '500ms'}, 'led_strip_0_led_4': {'color': 'AABBCC', 'fade': '500ms'}, 'led_strip_0_led_3': {'color': 'AABBCC', 'fade': '500ms'}, 'led_strip_0_led_2': {'color': 'AABBCC', 'fade': '500ms'}, 'led_strip_0_led_1': {'color': 'AABBCC', 'fade': '500ms'}, 'led_strip_0_led_0': {'color': 'AABBCC', 'fade': '500ms'}} >> Config validation error: Entry light_player:light_player:color = "[120, 0, 0]" is not valid. List or dict are not string Error Code: CFE-ConfigValidator-5 (https://docs.missionpinball.org/en/0.56/logs/CFE-ConfigValidator-5.html)
```

Does that work for someone or can someone spot what might be wrong?

The part of my show config file looks like this
```
#show_version=5

- duration: 100ms
  lights:
    pre_1_post:
      color: green
      fade: 100ms
    pre_2_post:
      color: AABBCC
      fade: 100ms
    pre_3_post:
      color: [100,0,0]
      fade: 100ms
```

number 1 and 2 work fine.

Thanks!

**Comment by atummons** [comment]
The log you sent and the code below are not the same.  The log references a
value of "[120, 0, 0]".  I am not sure if you put the quotes which broke
it, or if that is just how it is being handled in the logger.  Can you send
the code that matches the error?

**Comment by worldpeace-germany** [comment]
It is the logger, I just took the output from two different tests, anyways, here a matching example:


```
#show_version=5

- duration: 500ms
  lights:
    led_strip_0_led_0:
      color: [255,255,255]
      fade: 500ms
    led_strip_0_led_1:
      color: red
      fade: 500ms

- duration: 500ms
  lights:
    led_strip_0_led_0:
      color: red
      fade: 500ms
    led_strip_0_led_1:
      color: blue
      fade: 500ms
```
and the log

`mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Show "attract_light_show_opt6" >> Failed to load config player attract_light_show_opt6:lights with settings {'led_strip_0_led_0': {'color': [255, 255, 255], 'fade': '500ms', 'priority': 0}, 'led_strip_0_led_1': {'color': 'red', 'fade': '500ms'}} >> Config validation error: Entry light_player:light_player:color = "[255, 255, 255]" is not valid. List or dict are not string Error Code: CFE-ConfigValidator-5 (https://docs.missionpinball.org/en/0.56/logs/CFE-ConfigValidator-5.html)`
