### DISCUSSION TITLE
variable_player in machine file

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#118] [Q&A]
Hello,

here https://missionpinball.org/config/variable_player/ it says that variable_player is valid in machine config. Machine config is for me the mail config.yaml file. If I have a variable_player in there I get

`mpf.exceptions.config_file_error.ConfigFileError: Config File Error in variable_player: Section not valid outside of game modes.`

Am I having a misunderstanding what is meant here, or is either the documentation or the code buggy?

Thanks!

**Comment by toomanybrians** [comment]
Interesting. It seems your understanding is correct, based on that error.

I use the `variable_player:` in a machine config file in this test: https://github.com/missionpinball/mpf/blob/dev/mpf/tests/machine_files/fast/config/audio.yaml

Of course it's with `action: add_machine` since obv a player variable change won't work outside of an active game. So I wonder if you just need the action to specify that it's a machine var?

**Comment by worldpeace-germany** [comment]
That was the right hint!

This doesn't work

```
machine_vars:
  my_var:
    initial_value:  5
    
variable_player:
  game_started:
    my_var: 4
```


This works

```
machine_vars:
  my_var:
    initial_value:  5
    
variable_player:
  game_started:
    my_var:
      action: add_machine
      int: 4
```

For me, I have clearly defined a machine(!!) variable, so I thought the non-working example should know that I want to add to a machine variable. I will create a pull request for the docs in the next days to make that clearer. Would be nice if you can accept that pull request then. I hope it makes things for other people easier, I spent quite some time on this. I saw the set_machine option, not sure if I was just too stupid to draw the right conclusion, maybe I was too focused that mpf should know that I have machine var. Anyways, thanks!
