### DISCUSSION TITLE
queue_relay_player consistency problem

### DISCUSSION THREAD

**Discussion by ohmbrew** [missionpinball/missionpinball#13] [Q&A] [answered]
Hello smart folks. I'm really close to getting my custom pong table mech working using native MPF config code. Here's the issue. I have two ball holds are that are releasable via two coils (pongcup1 and pongcup2). When my multiball starts, the game attempts to eject both of the coils at very near the same time. Well, I need to intercept those because I need to rotate my mech before releasing each coil. Here's my queue_relay_player I've been playing with to help me with that:

```
queue_relay_player:
  balldevice_bd_pongcup1_ball_eject_attempt:
    post: pongcup_1_release_show
    wait_for: pongcup_1_moved
  balldevice_bd_pongcup2_ball_eject_attempt:
    post: pongcup_2_release_show
    wait_for: pongcup_2_moved

show_player:
  pongcup_1_release_show:
    pongtable_show:
      show_tokens:
        cup: 1
      loops: 0
pongcup_2_release_show:
    pongtable_show:
      show_tokens:
        cup: 2
      loops: 0
```

The pongtable_show simply takes a token and instructs the servo to move to that position, and then pongcup_X_moved event gets fired. Well, pongcup2_release_show is clobbering pongcup1_release_show, and so pongcup_1_moved event never gets fired.

I have my state machine setup that properly moves the table to proper positions as balls are locked. What kind of glue logic do I need to ensure the "other event" is not interfering? Best I can map out, here are the cases where the coils would be fired:
1. Multiball is not running. Both coils could be fired during collecting_balls. Or at the end of the game to release the balls.
2. Multiball is running. Both coils are fired because multiball has started and MPF is getting those balls from the mech.
3. Multiball is running. Player has shot into pongcup1. I'd like to release that immediately.

Greg

**Comment by ohmbrew** [comment]
I think I've figure it out. Has worked several test runs now, between ball ends and even multiple players. First thing, I had to remove persist_state: True from my multiball. It wasn't getting to the proper state modes when my multiball mode would restart between ball drains. Second thing, I looked at the logic of when pongcup2 would ever be released, and realized it was always when pongcup1 is also being released, so I modified what event the queue_relay for ejecting pongcup2 is waiting on. Lastly, I added another conditional event to pongcup1 eject_attempt - to check if multiball is running and pongcup2 does not have a ball.

I'll include my final code in case it helps anyone else:

```
# cases where MPF will try to eject from pongcups
# 1. Multiball not running: Both coils are activated simultaneously (e.g. collecting_balls, or on reset)
# 2. Multiball running: Both coils activated on start_multiball
# 3. Multiball running: Only pongcup1 coil activated (e.g. player hit pongcup1 during multiball - release immediately)
queue_relay_player:
  # check if pongcup2 has a ball. If so, play releaseall show
  balldevice_bd_pongcup1_ball_eject_attempt{device.switches.s_pongcup2.state == 1}:
    post: pongcup_all_release_show
    wait_for: pongcups_released
  # should only be attempting eject if we also are ejecting pongcup1. Which should be handled above
  balldevice_bd_pongcup2_ball_eject_attempt:
    post: pongcup_2_waiting_for_releaseall_show_to_finish   # dummy event
    wait_for: pongcups_released   # this waits on pongcup_all_release_show to finish
  # Check if we are in multiball and pongcup2 does NOT have a ball. Means balls have already been released for multiball and player hit pongcup1. Release immediately.
  balldevice_bd_pongcup1_ball_eject_attempt{device.state_machines.multiball.state == "multiball_running" and device.switches.s_pongcup2.state == 0}:
    post: pongcup_1_release_show
    wait_for: pongcup_1_moved

show_player:
  pongcup_all_release_show:
    pongtable_releaseall_show:
      loops: 0
  pongcup_1_release_show:
    pongtable_show:
      show_tokens:
        cup: 1
      loops: 0
```

**Comment by ohmbrew** [comment, marked as answer]
For completeness, I actually needed more conditionals than above. I think this is as simplified as I can get it, yet still covering all possible cases. Attaching here in case anyone can use this example, like I would have liked to have!

```
# cases where MPF will try to eject from pongcups
# 1. Multiball not running:
#    a. Pongcup1 has ball, Pongcup2 does not -> pongcup_1_release_show. This only moves the pongtable to place pongcup1 in a releaseable position.
#       Continued eject_attempt will release the ball from pongcup1.
#    b. Pongcup1 has ball, Pongcup2 has ball -> pongcup_releaseall_show. Both pongcups will release their balls in the show.
#       Continued eject_attempt logic will still happen, just balls will already be released. s'ok.
# 2. Multiball running
#    a. Pongcup1 has ball, Pongcup2 does not -> pongcup1_release_show. We have already released both balls for multiball, and player has sunk ball in pongcup1.
#       Ensure pongcup1 is in releasable position (run pongcup1_release_show), then allow eject_attempt logic to continue and ball will be released.
#    b. Pongcup1 has ball, Pongcup2 has ball -> pongcup_releaseall_show. Both pongcups will release their balls in the show.
#       Continued eject_attempt logic will still happen, just balls will already be released. s'ok.
queue_relay_player:
  # 1.a above
  balldevice_bd_pongcup1_ball_eject_attempt{device.state_machines.multiball.state != "multiball_running" and device.switches.s_pongcup2.state == 0}:
    post: pongcup_1_release_show
    wait_for: pongcup_1_moved
  # 1.b above
  balldevice_bd_pongcup1_ball_eject_attempt{device.state_machines.multiball.state != "multiball_running" and device.switches.s_pongcup2.state == 1}:
    post: pongcup_all_release_show
    wait_for: pongcups_released
  # 2.a above
  balldevice_bd_pongcup1_ball_eject_attempt{device.state_machines.multiball.state == "multiball_running" and device.switches.s_pongcup2.state == 0}:
    post: pongcup_1_release_show
    wait_for: pongcup_1_moved
  # 2.b above
  balldevice_bd_pongcup1_ball_eject_attempt{device.state_machines.multiball.state == "multiball_running" and device.switches.s_pongcup2.state == 1}:
    post: pongcup_all_release_show
    wait_for: pongcups_released  
  # should only get pongcup2 eject_attempt if we also are ejecting pongcup1 due to multiball. This should already be handled above, now we just wait for it to finish.
  balldevice_bd_pongcup2_ball_eject_attempt:
    post: pongcup_2_waiting_for_releaseall_show_to_finish   # dummy event
    wait_for: pongcups_released   # this waits on pongcup_all_release_show above to finish

show_player:
  pongcup_all_release_show:
    pongtable_releaseall_show:
      loops: 0
  pongcup_1_release_show:
    pongtable_show:
      show_tokens:
        cup: 1
      loops: 0
```
