### DISCUSSION TITLE
Variables in show_player

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#135] [Q&A]
Hello,

this is working fine:

```
show_player:
  ball_started:
    ball_num:
      show_tokens:
        txt: "{(current_player.ball):d}"
```
This is _not_ working fine, it doesn't show the content of the event variable, it shows the variable name:

```
show_player:
  player_turn_started:
    player_num:
      show_tokens:
        txt: player_turn_started.number
```
For the last txt I have tried all kind of braces, etc. around it. 

e.g.
"{(player_turn_started.number):d}"
"{(player_turn_started.number)}"
"{player_turn_started.number}"
... and probably a few more running out of ideas what combination I might have missed.

I am not getting it to show the content of that variable being posted

`INFO : EventManager : Event: ======'player_turn_started'====== Args={'player': <Player 1>, 'number': 1}`

So in this example I want to display obviously a 1.

Thanks.

**Comment by avanwinkle** [comment]
When pulling arguments, the period denotation indicates that the value should be pulled from the dictionary referenced before the period (e.g. `current_player`, `machine`, `game`, `settings`). When there is no period, the value should be pulled from the triggering event.

In your case, you'll want to use just "number" without "player_turn_started" in front.

```
show_player:
  player_turn_started:
    player_num:
      show_tokens:
        txt: "{(number):d}"
```
