### DISCUSSION TITLE
Bug or misunderstanding in shows

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#136] [Q&A] [answered]
Hello,

I have in my shows: section the following entry:
```

  game_end_animation:
    - time: 0
      segment_displays:
        neoSegTopLine:
          text: "GAME  OVER    "
          expire: 9s #how long the final text stays visible
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: left
    - time: 3
      segment_displays:
        neoSegBottomLine:
          text: (txt)
          expire: 6s #how long the final text stays visible
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: right
            #text: "*in*"
    - time: +10 #relative time after the previous step started, not ended
      segment_displays:
        neoSegTopLine:
          text: "Play again    "
          expire: 200s #how long the final text stays visible
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: left
```
I have 3 steps, the first two steps work absolutely fine, the third is giving me a headache. The third step has as time +10, I believe that is 10s after the previous step has started (not ended), documentation is not super clear on that. Now the text should flow in from right to left and stay for 200s before it expires and then of course the show should start again. I have the impression that the show starts **immediately** after the 3rd step has started. I see the P of (Play again) come in on the right, then the "Play again" is without further animation in its final position and the "GAME OVER" from the first step is being played. How can I convince mpf to keep the "Play again" for a certain time before advancing to the next step?

In addition I have changed the time: +10 to duration: 10s, then that step really takes 10s, BUT now I cannot control the start time. I have no idea what time it takes to start it. Maybe right after the second step has started, don't know. Anyways not too important, more important how can I control the start time AND duration at the same time?

Thanks!
