### DISCUSSION TITLE
Remove Text on a segment display

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#137] [Q&A] [answered]
Hello,

I want to wipe out the text on my segment display before I start to display a new text

```
  game_end_animation:
    - time: 0
      segment_displays:
        neoSegTopLine:
          text: "GAME  OVER    "
          expire: 9s #how long the final text stays visible
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: left
```

In the above example everything is working fine. Now I thought I replace _text_ by 18 spaces (18 because my display has 18 segments) so text: "                ". That simply doesn't do anything. It seems that the code checks for empty strings and then ignores this.

Background - maybe someone has another idea, my segments are ordered like this:

score 1      player     score2
score3       ball          score4

Once the game is over the first line shows GAME OVER (config example above). Then 3 seconds later the lower line should show "Player 1 won". But for these 3 seconds it still shows score3, ball and score4. I want to have this empty from the start

**Comment by avanwinkle** [comment]
What version of MPF are you running?

There are numerous examples and tests for the segment displays that successfully clear out the display with an empty string, although those just use `text: ""` instead of a bunch of spaces.

You may also want to enable debugging on your serial connection and see what commands are being sent to the segment displays, in case your hardware has special requirements that need to be considered.

**Comment by worldpeace-germany** [comment]
Hello,

EDIT: Tested on 0.80 now, same behavior.

I am on 0.56.1 - I know there are newer versions available but need to find to resetup mpf. I am running it on openSuse and it was in the past a bit troublesome. If you say it is a no-go on that version then I need to carve out that time somehow. I am using a Cobra neo segment.

Do you have a link how to enable debugging on the serial connection?

Anyways "" and " " seem to behave differently, but even a "" doesn't seem to work correctly. Maybe it is as well due to how the time parameter really works or my wrong understanding of the time parameter. Before I explain that let me past here the full relevant show, at the bottom of the post I will post my full neo seg config, just in case. In addition I can as well provide a video how the display behaves if needed. But now into the details

```
  game_end_animation:
    - time: 0
      segment_displays:
        neoSegTopLine:
          text: "GAME  OVER    "
          expire: 9s
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: left
    - time: +1
      segment_displays:
        neoSegBottomLine:
          text: ""
    - time: 3
      segment_displays:
        neoSegBottomLine:
          text: (txt)
          expire: 6s 
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: right
    - time: +10 
      segment_displays:
        neoSegTopLine:
          text: "PLAY  AGAIN   "
          expire: 8s 
          transition:
            type: push
            direction: left
          transition_out:
            type: split
    - duration: 8s
```
    
    
What do I want to achieve with the above:

a) As soon as the game ends I want to see the GAME OVER text flying in on the top row of my segments (8 + 2 + 8 digits)--> works perfectly fine
b) (3rd step) 3 seconds after the 1st step started I want to have a text fly in at the bottom row of my segment (again 8 + 2 + 8 digits) --> The flying in works fine
c) After 10s I want to display PLAY AGAIN and hold it for some time --> works perfectly fine

In step c I don't have to clear out the displays because the previous text has a transition_out set. I do not have to clear the top row at the beginning because as soon as the text flies in all digits are wiped out automatically even though at the beginning of the animation I would only need the very right digit. So the old text (points and player number) are not being moved out with the in transition (no problem for me), just mention it since I don't know if that is the correct behavior. Now let's get to the second step that is introduced to wipe out the bottom line, I tried various time parameters, like above +1, but as well 0.1, +0.1, 0 and 1. The 0 kills it completely and results in a crash of mpf. Goal is to wipe out the line right at the start so time: 0 would be final goal, but I can live with 0.1. Regardless what time I put in (except 0) the behavior is the following:

1. top line flies in
2. text on bottom line stays as it is
3. bottom line flies in
4. shortly after the fly in animation is done, the line is cleared, so now the second step has kicked in
5. bottom line shows shortly after again full text to transition_out

I tried as well (just top part of the example for better readability)


 ```
 game_end_animation:
    - time: 0
      segment_displays:
        neoSegTopLine:
          text: "GAME  OVER    "
          expire: 9s
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: left
        neoSegBottomLine:
          text: ""
```
          
So in the first step with time 0 I have both segments listed. Doesn't work either. Should it work?


With the 5 steps from above, either mpf doesn't behave correctly or I have not understood how the time parameter works. Would you say that my description is what you would expect with my config?

One additional question, the expire time parameter how is that calcualted?

i) it is only the time while the text is on its final position, so transition in and out are extra counted
ii) It starts to count with the transition in, plus the time without animation but transition_out is counted extra (since mpf might not know how long the transition takes)
iii) It is the total time including all transition (in and out) - thus mpf is smart enough to know how long the transitions are

Okay a long text, the more I appreciate an answer and like in the past I am willing to update the documentation to give back what I can give back.

Thanks,
Joe

PS: here the full config, just in case


```
#config_version=5

#Wiring: Ball --> Score 4 --> Score 2 --> Score 1 --> Score 3 --> Player
neoseg_displays:
  neoSegBall:
    start_channel: 1-0-0
    size: 2digit
    light_template:
      type: w
      subtype: led
  neoSegScore4:
    start_channel: 1-0-30
    size: 8digit
    light_template:
      type: w
      subtype: led
  neoSegScore2:
    start_channel: 1-0-150
    size: 8digit
    light_template:
      type: w
      subtype: led
  neoSegScore1:
    start_channel: 1-0-270
    size: 8digit
    light_template:
      type: w
      subtype: led
  neoSegScore3:
    start_channel: 1-0-390
    size: 8digit
    light_template:
      type: w
      subtype: led
  neoSegPlayer:
    start_channel: 1-0-510
    size: 2digit
    light_template:
      type: w
      subtype: led

segment_displays:
  displayBall:
    number: 1
    size: 2
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSegBall
      type: 14segment
  displayPlayer:
    number: 1
    size: 2
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSegPlayer
      type: 14segment
  displayScore1:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSegScore1
      type: 14segment
  displayScore2:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSegScore2
      type: 14segment
  displayScore3:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSegScore3
      type: 14segment
  displayScore4:
    number: 1
    size: 8
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 30
    platform_settings:
      light_groups:
        - neoSegScore4
      type: 14segment
  neoSegTopLine:
    number: 1
    size: 18
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 5
    platform_settings:
      light_groups:
        - neoSegScore1
        - neoSegPlayer
        - neoSegScore2
      type: 14segment
  neoSegBottomLine:
    number: 1
    size: 18
    integrated_dots: true
    use_dots_for_commas: true
    default_transition_update_hz: 5
    platform_settings:
      light_groups:
        - neoSegScore3
        - neoSegBall
        - neoSegScore4
      type: 14segment
    
show_player: #evtl. ändern auf segment_display_player:
  ball_started:
    ball_num:
      show_tokens:
        txt: "{(current_player.ball):d}"
  player_score{player_num==1}:
    p1_score:
      show_tokens:
        txt: "{(players[0].score):d}"
  player_score{player_num==2}:
    p2_score:
      show_tokens:
        txt: "{(players[1].score):d}"
  player_score{player_num==3}:
    p3_score:
      show_tokens:
        txt: "{(players[2].score):d}"
  player_score{player_num==4}:
    p4_score:
      show_tokens:
        txt: "{(players[3].score):d}"
  player_added{num==2}:
    p2_score:
      show_tokens:
        txt: " 0"
  player_added{num==3}:
    p3_score:
      show_tokens:
        txt: " 0"
  player_added{num==4}:
    p4_score:
      show_tokens:
        txt: " 0"
  player_turn_started:
    player_num:
      show_tokens:
        txt: "{(current_player.number):d}"
  mode_game_started:    #reset 
    p1_score:
      show_tokens:
        txt: ""
    p2_score:
      show_tokens:
        txt: ""
    p3_score:
      show_tokens:
        txt: ""
    p4_score:
      show_tokens:
        txt: ""
    game_end_animation:
      action: stop
  game_ended{machine.player1_score > machine.player2_score}:
    game_end_animation:
      show_tokens:
        txt: "PLAYER 1 WON     "
  game_ended{machine.player2_score > machine.player1_score}:
    game_end_animation:
      show_tokens:
        txt: "PLAYER 2 WON     "

shows:
  ball_num:
  - duration: -1
    segment_displays:
      displayBall:
        text: (txt)
  player_num:
  - duration: -1
    segment_displays:
      displayPlayer:
        text: (txt)
  p1_score:
  - duration: -1
    segment_displays:
      displayScore1:
        text: (txt)
  p2_score:
    - duration: -1
      segment_displays:
        displayScore2:
            text: (txt)
  p3_score:
    - duration: -1
      segment_displays:
        displayScore3:
          text: (txt)
  p4_score:
    - duration: -1
      segment_displays:
        displayScore4:
          text: (txt)
  game_end_animation:
    - time: 0
      segment_displays:
        neoSegTopLine:
          text: "GAME  OVER    "
          expire: 9s #how long the final text stays visible
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: left
    - time: +1
      segment_displays:
        neoSegBottomLine:
          text: ""
    - time: 3
      segment_displays:
        neoSegBottomLine:
          text: (txt)
          expire: 6s #how long the final text stays visible
          transition:
            type: push
            direction: left
          transition_out:
            type: push
            direction: right
            #text: "*in*"
    - time: +10 #relative time after the previous step started, not ended
      segment_displays:
        neoSegTopLine:
          text: "PLAY  AGAIN   "
          expire: 8s #how long the final text stays visible
          transition:
            type: push
            direction: left
          transition_out:
            type: split
            #direction: left
    - duration: 8s

```
