### DISCUSSION TITLE
mpf changes for color in version 0.80

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#138] [Q&A] [answered]
This about a potential change in mpf 0.80 (or a regression), in my older 0.56 setup this works fine
```

- duration: 200ms
  lights:
    flasherDomeTop_light_0:
      color: 51002d
      fade: 100ms
    flasherDomeTop_light_1:
      color: 01002d
      fade: 100ms
```

in 0.80 the leading 0 is an issue, I need now
```

- duration: 200ms
  lights:
    flasherDomeTop_light_0:
      color: 51002d
      fade: 100ms
    flasherDomeTop_light_1:
      color: '01002d'
      fade: 100ms
```

so values with leading 0 needs to be single quoted. If that is intended, then it should be mentioned in the changes / migration document, if it is not intended then it should be fixed please. Does someone know?
