### DISCUSSION TITLE
Mode configured to stop playing song when mode ends but configuration is invalid

### DISCUSSION THREAD

**Discussion by bernarma** [missionpinball/missionpinball#142] [Q&A] [answered]
In the documentation the sound_player configuration item indicates you can specify the "mode_end_action" property but when attempting to start mpf it indicates that this is NOT valid.

![image](https://github.com/user-attachments/assets/de3b9a13-b63c-4f4b-a43a-2e057bb4cc19)

Referring to this documentation: https://missionpinball.org/config/sound_player/#mode_end_action it appears as though it is supported. I have checked the installed version of MPF config_spec.yaml and that configuration property is NOT present which confirms the behavior I am seeing but looking at the master/main branch in GitHub I can see that the config_spec.yaml file has it.

The question I have, will this be coming in future dev builds? I am using Mission Pinball Framework v0.80.0.dev4 or is this going to be deprecated and if so, is there an alternate way of stopping a music file when a mode ends? Thanks for your assistance.

**Comment by avanwinkle** [comment]
You are correct, this config option was not migrated to MPF 0.80 and the default behavior is (or should be!) to stop all mode-based sounds when a mode stops.

The MPF mechanism for this is called "context", where each sound/slide/widget is played with its mode as the context and when a mode ends, a "clear" event is triggered with the mode name as an argument and all active sounds/slides/widgets with that name as their context will be gracefully removed.

For cases when this is not desired, you can manually specify your own context in the config player and your asset will respond to that context instead, so you can/must manually clear it.

If you are triggering a sound in a mode through sound_player and that sound is not stopping when the mode stops, I would love to see your logs to determine what the bug is.

**Comment by bernarma** [comment]
Thanks for your explanation. That makes sense. I have attached both logs and snippets from the mode config files (song2.yaml is effectively the same as song1.yaml). The godot file is included as it shows when it started playing the song. In godot, the music files are in the sounds directory called song1.wav with a corresponding song1.tres and a song2.wav and song2.tres. Hopefully this helps.

#song_select.yaml
```
mode:
  start_events: start_mode_song_select
  stop_events: song_select_item_selected
  code: mpf.modes.carousel.code.carousel.Carousel

mode_settings:
  selectable_items: song1, song2
  select_item_events: s_lockdown_active # or ball plunge
  next_item_events: s_flipper_left_active
  previous_item_events: s_flipper_right_active

variable_player:
  item_highlighted:
    selected_song:
      string: (item)
      action: set

event_player:
  item_highlighted{item=="song1"}:
    - mode_Song_CHANGE
    - mode_Song_1_start
  item_highlighted{item=="song2"}:
    - mode_Song_CHANGE
    - mode_Song_2_start
```

#song1.yaml
```
mode:
  start_events: ball_started{current_player.selected_song=="song1"}, mode_Song_1_start, timer_song2_timer_complete
  stop_events: ball_ending,mode_Song_CHANGE,timer_song1_timer_complete
  restart_on_next_ball: true

sound_player:
  mode_song1_started:
    song1:
      action: play
      loops: 0
      volume: 0.25
```

[godot.log](https://github.com/user-attachments/files/16576612/godot.log)
[godot2024-08-12T08.15.21.log](https://github.com/user-attachments/files/16576613/godot2024-08-12T08.15.21.log)
