### DISCUSSION TITLE
Same underlying shot but requires different (but dependent) behavior across multiple modes (with different priorities)

### DISCUSSION THREAD

**Discussion by bernarma** [missionpinball/missionpinball#150] [Q&A]
To set some context, I have 7 unique shots that are defined in a base/global mode that run throughout the game.

Base/Global Mode:
```
shots:
  sh_shot1:
    switch: s_switch1
  sh_shot2:
    switch: s_switch2
```

I have another mode that runs alongside this base/global mode that defines its own set of shots (ultimately still the same 7 unique shots from the base) configured using the hit_event property of the corresponding shot from the base/global mode.

Mode 1 Shots
```
shots:
  sh_mode1_shot1:
    hit_events: sh_shot1
    enable_events: enable_shot1
    disable_events: disable_shot1
    profile: custom_profile1
  sh_mode1_shot2:
    hit_events: sh_shot2
    enable_events: enable_shot2
    disable_events: disable_shot2
    profile: custom_profile1
```

What I would like to do is have a new mode start, that for any shot that the other mode has not "enabled" (i.e. lit up), to be actively lit in this new mode so I can tie some logic to it (keeping in mind that the other mode that is running has the potential to change its active/enabled shots at any time and this mode must respect that).

Mode 2 Shots
```
shots:
  sh_mode2_shot1:
    hit_events: sh_shot1
    profile: custom_profile2
  sh_mode2_shot2:
    hit_events: sh_shot2
    profile: custom_profile2
```

I am unsure after reading through the documentation on how to approach this. I have read about shot profiles and the block property but haven't been able to work it out. I was hoping someone would have some suggestions on how to tackle this problem.
