### DISCUSSION TITLE
Score points not always counted

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#152] [Q&A] [answered]
Hello,

mpf 0.80 is what I use. I have a problem that sometime points are not being awarded on hit. 

I have a variable player

```
variable_player:
  s_pop_bumper_1_active: #yellow
    score: 100
  s_pop_bumper_2_active: #orange
    score: 200
  s_pop_bumper_3_active: #red
    score: 300
  s_slingshot_right_active: 
    score: 50
  s_slingshot_left_active: 
    score: 50
```

and sometimes - gut feeling 20-30% of the cases - when for example the slingshot is hit no points are scored - but the slingshot fires so the switch must have been active.

Anyone an idea or have seen the same issue?

Thanks!
