### DISCUSSION TITLE
How to initialise player values with a setting ?

### DISCUSSION THREAD

**Discussion by gbouthenot** [missionpinball/missionpinball#153] [General]
I would like to initialise a player variable with a value **stored in the settings**.

I tried to have the player_vars in the config file this way:

```yaml
player_vars:
  myvalue:
    initial_value: settings.myvaluefromsetting
```

And a settings:

```yaml
settings:
  myvaluefromsetting:
    label: "the initial value"
    values:
      0: "enable feature"
      1: "1 bash needed"
      2: "2 bash needed"
      3: "disable feature"
    default: 1
    key_type: int
```

But Unfortunately, mpf crashes at start:

```
ValueError: invalid literal for int() with base 10: 'settings.myvaluefromsetting'
```

It appears that players_vars -> initial_value can not use placeholder value.

So how can I do to initialise the values I want the user can customise ?
I though of a "proxy" mode that do all the initialisation, is it the way to go ?
