### DISCUSSION TITLE
Prevent the auto-plunging of a ball to the playfield from the plunger lane when a physical multiball_lock captures ball?

### DISCUSSION THREAD

**Discussion by bernarma** [missionpinball/missionpinball#159] [Q&A] [answered]
I have a multiball lock that when a ball is captured it automatically plunges the ball from the trough -> plunger -> playfield - this plunger has been configured as follows:

```
ball_devices:
  bd_plunger:
    ball_switches: s_plunger_lane
    eject_coil: c_plunger
    mechanical_eject: true
    ball_missing_timeouts: 10s
    eject_timeouts: 3s
    entrance_count_delay: 600ms # down from 900ms
    player_controlled_eject_event: force_plunger_launch
    ball_search_order: 1
    eject_coil_retry_pulse: 50ms
    retries_before_increasing_pulse: 3
    max_eject_attempts: 6
```

Is there a way to prevent the automatic plunging of the ball to the playfield and let the player control this using the mechanical action instead?

The area of code I have traced down the function is here - last line does not provide additional parameters to the add_ball function - basically I would like the player_controlled to be set to true:

multiball_lock.py
```
    def _request_new_balls(self, balls):
        """Request new ball to playfield."""
        balls_added = 0
        for device in self._source_devices:
            balls_to_add = max(min(device.available_balls, balls - balls_added), 0)
            device.eject(balls=balls_to_add, target=self.source_playfield)
            balls_added += balls_to_add

        self.source_playfield.add_ball(balls=max(balls - balls_added, 0))
```

ball_device.py
```
    def add_ball(self, balls=1, source_device=None,
                 player_controlled=False) -> bool:
```

Context: MPF 0.8 (latest from Github)
