### DISCUSSION TITLE
Configuration Settings using a Generator as opposed to hard coded values

### DISCUSSION THREAD

**Discussion by bernarma** [missionpinball/missionpinball#161] [Ideas]
I would like to propose an enhancement to the existing Configuration Settings in MPF. Currently if I am configuring ball save time as a configurable property (as follows):

```
  ball_save_time:
    label: "Ball Save Time"
    settingType: standard
    sort: 90
    default: 9
    key_type: int
    values:
      0: 0
      1: 1
      2: 2
      3: 3
      4: 4
      5: 5
      6: 6
      7: 7
      8: 8
      9: 9
      10: 10
      ....
      60: 60
```

I need to create one row per value. My proposal is to enhance this to support a min/max and increment value as follows (this would only work for numerical values):

```
  ball_save_time:
    label: "Ball Save Time"
    settingType: standard
    sort: 90
    default: 9
    key_type: int
    min_value: 0
    max_value: 60
    inc_value: 1
```

The question is, would this be a contribution to the framework you would like or should I implement this locally?
