### DISCUSSION TITLE
Picture in Picture question

### DISCUSSION THREAD

**Discussion by Pucksnok** [missionpinball/missionpinball#2] [Q&A]
Hi.
I'm expanding my game and I'm trying to learn how the picture in picture are working.

I use the code below and I'm starting to get a bit frustrated because the upper_right_display is covering the whole default display with its black background, after the slide expires (3s) the other slide is shown so it's created as it should but the first slide is covering the whole screen. I don't get why the music_player_slide is covering the whole monitor, in my world it should be 600x400 (since I use the source_display: upper_right_display) and the other slide should be shown behind. Any directions where I do this wrong would be appreciated. 

I have also tried to use the target: upper_right_display in the slide player but then it isn't shown at all.

**Here's my code I'm trying...**

```
#config_version=5

mode:
    start_events: mode_base_started, mode_attract_started
    stop_events: mode_music_player_stopped
    priority: 100
    game_mode: false


event_player:
    attract_music1_played:
      - attract_music1_played_show_slide


slide_player:
    attract_music1_played_show_slide.1: music_player_slide
    attract_music1_played_show_slide.2: music_player_slide2

slides:
    music_player_slide:
        widgets:
          - type: display
            width: 600
            height: 400
            source_display: upper_right_display
          - type: text
            text: SHOW TEXT ON DISPLAY 600x400
            color: white
            font_size: 99
            x: 200
            y: 200
            anchor_x: left
            anchor_y: bottom
        background_color: black
        expire: 3s
    music_player_slide2:
        widgets:
          - type: text
            text: SHOW TEXT ON DEFAULT DISPLAY
            font_size: 88
            color: yellow
        background_color: red
`

Display settings...
#config_version=5

displays:
    window:
        width: 2560
        height: 1440
        default: true
    upper_right_display:
        width: 600
        height: 400
       
window:
        width: 2560
        height: 1440
        title: Testing
        maxfps: 60
        show_cursor: no
        resizable: no
        borderless: true
        fullscreen: no
        exit_on_escape: true
        source_display: window


```
