### DISCUSSION TITLE
(solved) events_when_activated on a switch doesn't seem to work

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#24] [Q&A] [answered]
Hi,

part of my virtual config is

```
keyboard:
    s:
        switch: s_start
    1:
        event: blubber
    f:
        switch: s_right_flipper

switches:
    s_left_flipper:
        number: 1 
        tags: left_flipper
    s_right_flipper:
        number: 2
        tags: right_flipper
        events_when_activated: bla
        events_when_deactivated: bla2
    s_start:
        number: 11
        tags: start

```

What works:
- I press the key "1" and the event "blubber" is shown in mpf monitor
- I press f and I see in the mpf console that the switch is highlighted green, so it is pressed

What doesn't work:
upon pressing "f" I would expect to see an event bla (and subsequently bla2) in the mpf monitor, but I don't. What is missing when a switch should fire an event? For now the switch should be simulated by the keyboard. I don't want to fire just an event with the keyboard like I do with key "1".

Any ideas?

**Comment by cobra18t** [comment]
Does anything different happen if you fire the switch by clicking the switch in the MPF Monitor's Playfield window? 

There are some goofy things about the keyboard emulation of switches so I usually don't use it.

**Comment by worldpeace-germany** [comment]
I have to admit I am very new to mpf and running through the tutorial (plus a bit left and right). I am not able to find a step in that tutorial (or elsewhere) how  to create such a playfield. Is that missing or am I just not looking at the right places? Apart from that if they are goofy, if you can give me a hint where in the Python code I can find the relevant code snippet I could try to see if I can spot why it is not working for me.

**Comment by colemanomartin** [comment]
Monitor is not in the tutorial.  But there is a nice text introduction and video that Jan made.  
https://docs.missionpinball.org/en/stable/tools/monitor/index.html

**Comment by worldpeace-germany** [comment]
Thanks for the link, I read and watched it. In that video Jan just drags the elements onto the playfield to have them there. When I try to drag an item over from the device window onto the playfield window then nothing happens. Is there some prerequisite before I can do that? When I drag a switch over I see on the playfield window that my mouse pointer gets an overlay with a little red circle and a red line to indicate that this is not allowed/possible.

**Reply by cobra18t** [reply]
Have you placed a playfield image there? Not sure if it requires an image or not.

**Reply by worldpeace-germany** [reply]
I have not - I would not know how.... Just drag and drop an image from the file system gives me again this mouse pointer overlay to show it is forbidden. How do you add your images to the playfield?

**Reply by cobra18t** [reply]
Step 2 and 3 here should help: https://docs.missionpinball.org/en/stable/tools/monitor/running.html

**Reply by worldpeace-germany** [reply]
Yes you need an image for the playfield before you can drag switches to it. Anyways, the behavior is the same as before. I click on the image for my switch, I see in the console that the switch is triggered but I don't see my event. When clicking on the start button, then I do see the event to start the game.

**Comment by worldpeace-germany** [comment]
Hello,

I received my Cobra board :-)  now I wanted to test the same on the Cobra board. In short: same issue.

My config

```
#config_version=5

hardware:
   platform: opp
   driverboards: gen2

opp:
   ports: /dev/ttyACM0, /dev/ttyACM1

switches:
    my_test_switch:
        number: 0-0-16
        tags: my_nice_switch
        events_when_activated: switch_active
        events_when_deactivated: switch_inactive
```
I see that my switch is being pressed in the monitor. I do not see any events in the event monitor.  Am I completely on the wrong path here or is something really broken in mpf here? Can someone test the above config on their hardware?

Thanks!
