### DISCUSSION TITLE
Preventing auto-plunge after a ball is locked

### DISCUSSION THREAD

**Discussion by sjkowal** [missionpinball/missionpinball#3] [Q&A] [answered]
I've implemented a three ball multi-ball with a two ball physical lock device.  Whenever a ball is locked and replaced through the trough it's auto-plunged out of the shooter lane. I'd like to prevent the auto-plunge so that the player can manually plunge the ball. It seems like this should be built into the multiball or multiball_lock but I can't figure out how to configure this behavior.  I've thought about ball_holds and queue_relay_player but neither of these seem to do what I need. Does anyone have any ideas on how I might solve this problem?

Here's an example of how I have the ball devices and multiball configured.

config/config.yaml
```
#config_version=5
#multiball_noplunge 

hardware:
  platform: p3_roc

p_roc:
  driverboards: pdb

displays:
  window:
    width: 1366 
    height: 768 

game:
    balls_per_game: 3

ball_devices:
  bd_drain:
    ball_switches: s_trough_one, s_trough_two, s_trough_three, s_trough_four 
    eject_coil: c_trough_eject
    tags: drain, home, trough
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 3s
  bd_plunger:
    eject_coil: c_auto_plunge
    ball_switches: s_shooter_lane
    mechanical_eject: true 
    auto_fire_on_unexpected_ball: true 
    eject_timeouts: 3s
  bd_locks:
    ball_switches: s_ball_one_lock, s_ball_two_lock, s_ball_three_lock 
    eject_coil: c_lock_release
    eject_timeouts: 2s


playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

virtual_platform_start_active_switches: s_trough_one, s_trough_two, s_trough_three, s_trough_four

switches:
  s_start:
    number: A0-B0-5
    tags: start

  s_trough_jam:
    number: A1-B0-3
    type: 'NC'    
  s_trough_one:
    number: A1-B0-4 
    type: 'NC'    
  s_trough_two:
    number: A1-B0-7
  s_trough_three:
    number: A1-B0-6
  s_trough_four:
    number: A1-B0-5

  s_shooter_lane:
    number: A1-B1-4

  s_ball_one_lock:
    number: A1-B0-2 
    type: 'NC'
  s_ball_two_lock:
    number: A1-B0-1 
    type: 'NC'
  s_ball_three_lock:
    number: A1-B0-0 
    type: 'NC'
  
  s_test_1:
    number: A1-B1-0
    tags: test_1 
  s_test_2:
    number: A1-B1-1 
    tags: test_2 

coils:
  c_auto_plunge:
    number: A0-B1-2 
  c_trough_eject:
    number: A0-B1-3
    default_pulse_ms: 20
  c_lock_release:
    number: A0-B0-6
    default_pulse_ms: 120

modes:
  - multiball 
```

modes/multiball/config/multiball.yaml

```#config_version=5
##! mode: multiball 

mode:
  start_events: ball_starting
  priority: 101

variable_player:
  s_test_1_active:
    score: 100 
  s_test_2_active:
    score: 100 

event_player:
  s_test_1_active:
    - test_event1 
  s_test_2_active:
    - test_event2

multiball_locks:
  madnesslock:
    balls_to_lock: 2
    lock_devices: bd_locks 
    locked_ball_counting_strategy: virtual_only
    enable_events: enable_lock
    disable_events: disable_lock
    reset_count_for_current_player_events: multiball_lock_madnesslock_full
multiballs:
  madnessmball:
    ball_count: 3
    ball_locks: bd_locks 
    start_events: start_multiball
  
state_machines:
  multiball: 
    states:
      start:
        label: lock not enabled
      lock_enabled:
        label: lock enabled 
        events_when_started: enable_lock
        events_when_stopped: disable_lock
      multiball_available:
        label: multiball can be ball_started
      multiball_running:
        label: multiball start_running
        events_when_started: start_multiball
    transitions: 
      - source: start
        target: lock_enabled
        events: test_event1 
      - source: lock_enabled
        target: multiball_available
        events: multiball_lock_madnesslock_full
      - source: multiball_available
        target: multiball_running
        events: test_event2 
      - source: multiball_running
        target: start
        events: multiball_lock_madnesslock_full
```

**Comment by mwiz** [comment]
Did you try to set  `auto_fire_on_unexpected_ball` to false under `bd_plunger`? and see what happens?  I think there are some setting there you can adjust(?)

**Reply by sjkowal** [reply]
I tried setting auto_fire_on_unexpected_ball to false, but it didn't solve the issue. I think the bd_drain and bd_plunger devices are working together. In this case the ball is expected to be sent to the bd_plunger. The auto-plunge fires the ball regardless if this is set to true or false.

**Comment by mwiz** [comment]
okay.  Another suggestion might be to try a ball_holds for the plunger lane that is enabled on multiball start?  (just guessing tho)

**Reply by sjkowal** [reply]
I tried using a ball_holds with the bd_plunger but it doesn't trigger holding the ball when the ball is being fed by the bd_drain device after the lock.

**Comment by cobra18t** [comment]
You may need to disable the ball replace from the multiball lock entirely. The multiball lock replace requests the ball to go to the playfield. The machine tries to get it to the playfield as fast as possible which includes the auto plunge.

Try setting balls_to_replace to 0 in the multiball lock and use request_ball_events in the plunger lane to request balls after a ball lock. Be careful, because I am sure there are some race conditions that could leave you with no balls in play or too many.

**Reply by sjkowal** [reply]
I have tried this. Setting balls_to_replace to 0 with a request_ball_events does have the desired effect of ejecting a ball into the bd_plunger device and not triggering the auto plunge. Unfortunately MPF seems to be in a bad state.  If this new ball is drained it recognizes the ball in the bd_drain device and triggers the end of ball and the beginning of a new one but a ball is never ejected into the shooter lane. I've also noticed the state of the bd_plunger after the a ball is requested from a lock is set to idle even though there is a ball in the shooter lane that's just been ejected from the bd_drain device. I would expect the state to be ejecting.  It seems to suggest there's a bug with the ball tracking between devices.  I've also seen instances where the game always auto plunges on a new ball.

**Comment by cobra18t** [comment, marked as answer]
You could remove the coil from the ball device and setup that coil separately to only plunge on the events you decide. It is more manual, but then the device does not try to get too "smart."

**Reply by sjkowal** [reply]
I finally got around to trying out this approach. It seems like it works well enough but you need to account for any ball savers, e.g. multball, ball_save.  Here's what my solution looks like using the example from above.

config/config.yaml

```
#config_version=5
# multiball_noplunge 

hardware:
  platform: p3_roc

p_roc:
  driverboards: pdb

displays:
  window:
    width: 1366 
    height: 768 

game:
    balls_per_game: 3

ball_devices:
  bd_drain:
    ball_switches: s_trough_one, s_trough_two, s_trough_three, s_trough_four 
    eject_coil: c_trough_eject
    tags: drain, home, trough
    jam_switch: s_trough_jam
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 2s
  bd_plunger:
    ball_switches: s_shooter_lane
    mechanical_eject: true 
    eject_timeouts: 2s
  bd_locks:
    ball_switches: s_ball_one_lock, s_ball_two_lock, s_ball_three_lock 
    eject_coil: c_lock_release
    eject_timeouts: 2s


playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

virtual_platform_start_active_switches: s_trough_one, s_trough_two, s_trough_three, s_trough_four

autofire_coils:
  auto_plunge:
    coil: c_auto_plunge
    switch: s_shooter_lane
    disable_events: disable_auto_plunge
    enable_events: enable_auto_plunge
    coil_overwrite:
      recycle: True 
      pulse_power: 1 

switches:
  s_start:
    number: A0-B0-5
    tags: start

  s_trough_jam:
    number: A1-B0-3
    type: 'NC'    
  s_trough_one:
    number: A1-B0-4 
    type: 'NC'    
  s_trough_two:
    number: A1-B0-7
  s_trough_three:
    number: A1-B0-6
  s_trough_four:
    number: A1-B0-5

  s_shooter_lane:
    number: A1-B1-4

  s_ball_one_lock:
    number: A1-B0-2 
    type: 'NC'
  s_ball_two_lock:
    number: A1-B0-1 
    type: 'NC'
  s_ball_three_lock:
    number: A1-B0-0 
    type: 'NC'
  
  s_test_1:
    number: A1-B1-0
    tags: test_1 
  s_test_2:
    number: A1-B1-1 
    tags: test_2 

coils:
  c_auto_plunge:
    number: A0-B1-2 
  c_trough_eject:
    number: A0-B1-3
    default_pulse_ms: 40
  c_lock_release:
    number: A0-B0-6
    default_pulse_ms: 120

modes:
  - multiball 
```

modes/multiball/config/multiball.yaml
```
#config_version=5
##! mode: multiball 

mode:
  start_events: ball_starting
  priority: 101
 
variable_player:
  s_test_1_active:
    score: 100 
  s_test_2_active:
    score: 100 

event_player:
  s_test_1_active:
    - test_event1 
  s_test_2_active:
    - test_event2

multiball_locks:
  madnesslock:
    balls_to_lock: 2
    lock_devices: bd_locks 
    locked_ball_counting_strategy: virtual_only
    enable_events: enable_lock
    disable_events: disable_lock
    reset_count_for_current_player_events: multiball_lock_madnesslock_full
multiballs:
  madnessmball:
    ball_count: 3
    ball_locks: bd_locks 
    start_events: start_multiball
    shoot_again: 20s

ball_holds:
  bunker:
    balls_to_hold: 1
    hold_devices: bd_plunger
    priority: 10
    enable_events: test_event1 
  
state_machines:
  auto_plunge:
    states:
      start:
        label: autoplunce non-enabled
      auto_plunge_enabled:
        label: autoplunge ball
        events_when_started: enable_auto_plunge
        events_when_stopped: disable_auto_plunge
    transitions:
      - source: start
        target: auto_plunge_enabled
        events: multiball_madnessmball_started
      - source: auto_plunge_enabled
        target: start
        events: multiball_madnessmball_shoot_again_ended 

  multiball: 
    states:
      start:
        label: lock not enabled
      lock_enabled:
        label: lock enabled 
        events_when_started: enable_lock
        events_when_stopped: disable_lock
      multiball_available:
        label: multiball can be ball_started
      multiball_running:
        label: multiball start_running
        events_when_started: start_multiball
    transitions: 
      - source: start
        target: lock_enabled
        events: test_event1 
      - source: lock_enabled
        target: multiball_available
        events: multiball_lock_madnesslock_full
      - source: multiball_available
        target: multiball_running
        events: test_event2 # this should be an even when the playfield validates?
      - source: multiball_running
        target: start
        events: multiball_lock_madnesslock_full
```
