### DISCUSSION TITLE
Random values

### DISCUSSION THREAD

**Discussion by Pucksnok** [missionpinball/missionpinball#40] [Q&A]
Is there any way to generate a random x or y value for a animation or widget image/text?
For example I would like to set a random interval for a x value that's between 0 and 2560, or doing a random duration on my animation between 0.2 and 2 seconds.

I did search, searched and searched some more without finding anything. 

Cheers.

**Comment by Pucksnok** [comment]
I guess not then. 

Cheers.

**Reply by cobra18t** [reply]
I only know of the random_event_player in MPF and you may be able to use that to some degree. 

Do you have any python programming experience? If you added that feature, I am sure people would use it. If nothing else, you could add it to your own game as custom code: https://developer.missionpinball.org/en/dev/code/index.html

**Reply by Pucksnok** [reply]
Thanks, I don't any programming so same with Python but I guess I could try a bit, it worked out when I needed to get the time for a clock in mpf. Thx for a reply, glad I didn't miss something obvious. :)

Cheers.

**Reply by gbouthenot** [reply]
I tried to create a timer on mode start, that ticks quicky. Then the "random" value may be calculated with math modulus.
```
timers:
  main_timer:
    start_value: 0
    start_running: true
    tick_interval: .1s

variable_player:
  s_switch:
    score: (device.timers.main_timer.ticks) % 2560
```

And it works, Unfortunately, MPF creates an event for every ticks, and even with a low speed timer (10 times a second), it spams the events and make debugging hard.
Also the value can only be used if there is a placeholder for a dynamic value.
