### DISCUSSION TITLE
Having difficulty with getting the Virtual Segment Display to update score

### DISCUSSION THREAD

**Discussion by kylenahas** [missionpinball/missionpinball#43] [Q&A]
Hello all, 

I'm trying to begin to integrate a segment display into my game. I've followed the steps to create a virtual segment display in [How to setup and use the virtual segment display emulator](https://docs.missionpinball.org/en/latest/displays/widgets/segment_display_emulator/how_to.html).

The issue I'm having is that my segment widget will not update the score as the score changes. The text that I set as the initial text in the widget continues to display. Any suggestions on where to begin debugging this issue? Or any glaring issues I've overlooked?

Here is the info regarding my version of MPF and platform:
```
mpf_version: MPF v0.56.0-dev33
mpf_extended_version: MPF v0.56.0-dev33, Config...
python_version: 3.9.1
platform: Windows-10-10.0.19041-SP0
```

Here is a section from my `config.yaml`:

```yaml
displays:
  window:
    width: 800
    height: 600

segment_displays:
  display1:
    number: 1

virtual_segment_display_connector:
  segment_displays: display1


slides:
  window_slide_1:
    widgets:
      - type: segment_display_emulator
        name: display1
        character_count: 6
        display_type: 7seg
        character_slant_angle: 0
        character_spacing: 20
        segment_width: 0.11
        segment_interval: 0.04
        segment_off_color: 4b4c4a30
        segment_on_color: fe961bff
        side_bevel_enabled: true
        dot_enabled: false
        comma_enabled: false
        text: "000000"
        width: 600
        height: 150
        y: 100
```

And from `base.yaml`:

```yaml
segment_display_player:
  update_segment_display_score:
    display1:
      text: "{players[0].score:d}"
```

I tried this portion in config as well, but it also did not update the score. Additionally, I've tried several different text substitutions for the score. I think the issue is related to how `update_segment_display_score` is (not) getting called. Am I missing something else where I need to be posting an event to `update_segment_display_score`?
