### DISCUSSION TITLE
[Solved] Problem with multiple shots and shows

### DISCUSSION THREAD

**Discussion by Leeoneil-Vely** [missionpinball/missionpinball#44] [Q&A] [answered]
Hello !
I have a strange problem, I don't understand what's going on with "shots" and "shows".
It looks like there is some bug,or maybe i'm not creating my script the good way.
I hope you can help me on that (MPF last stable version).

The idea is to change LED color when bumpers and slingshots are hit.
It's working perfectly with the 3 bumpers.
When i add the "same code" for slingshot, everything start to be buggy (no light, or activate other light...)

In "base" mode, i have this in the config file :
```
shots:
  bumper_one_shot:
    switch: s_popbumper_one
    profile: bumper1_profile
  bumper_two_shot:
    switch: s_popbumper_two
    profile: bumper2_profile
  bumper_three_shot:
    switch: s_popbumper_three
    profile: bumper3_profile
  sling_left_shot:
    switch: s_sling_left
    profile: sling_left_profile
  sling_right_shot:
    switch: s_sling_right
    profile: sling_right_profile


shot_profiles:
  bumper1_profile:
    states:
      - name: bump1  # step 1
        show: bumper1_base_show
      - name: bump1_purple  # step 2
        show: bumper1_light_show
    loop: true
  bumper2_profile:
    states:
      - name: bump2  # step 1
        show: bumper2_base_show
      - name: bump2_purple  # step 2
        show: bumper2_light_show
    loop: true
  bumper3_profile:
    states:
      - name: bump3  # step 1
        show: bumper3_base_show
      - name: bump3_purple  # step 2
        show: bumper3_light_show
    loop: true
  sling_left_profile:
    states:
      - name: sling_left  # step 1
        show: sling_left_base_show
      - name: sling_left_purple  # step 2
        show: sling_left_light_show
    loop: true
  sling_right_profile:
    states:
      - name: sling_right  # step 1
        show: sling_right_base_show
      - name: sling_right_purple  # step 2
        show: sling_right_light_show
    loop: true
```

In the "shows" folder of my "base" mode, i have all these files :
bumper1_base_show.yaml
bumper1_light_show.yaml
bumper2_base_show.yaml
bumper2_light_show.yaml
bumper1_base_show.yaml
bumper3_light_show.yaml
bumper3_base_show.yaml
sling_left_base_show.yaml
sling_left_light_show.yaml
sling_right_base_show.yaml
sling_right_light_show.yaml
(lots of them, maybe it's the problem ?)

Inside each show, it's very simple.
Example for the first 2 files :
```
#show_version=5
- time: 0
  lights:
    led_48: 'white'
```

```
#show_version=5
- time: 0
  lights:
    led_48: 'purple'

```
If i programmed this way for the 3 bumpers, there is no problem.
When i add the slingshots, it's not working anymore (for the bumpers too it's starting to be random).

Is there another way to do this ?
(actually the "shows" are really simple, but i'd like to add a real show, with multiple LED each time it's been hitted)

Thank's for your help !
