### DISCUSSION TITLE
Addressing a single LED in define light_stripe

### DISCUSSION THREAD

**Discussion by worldpeace-germany** [missionpinball/missionpinball#46] [Q&A] [answered]
Hello,

I have the following config

```
#config_version=5

hardware:
   platform: opp
   driverboards: gen2

opp:
   ports: /dev/ttyACM0, /dev/ttyACM1


light_stripes: 
   led_strip_0:
      number_start: 0
      count: 50
      number_template: 0-0-{}
      light_template:
         type: rgb
         tags: strip0


light_player:
   full_strip_on:
      strip0: DFFF00
   led_off:
      led_strip_0: off
   first_led_green:
      0-0-0: green # does not work


keyboard:
   1:
      event: led_off
   2:
      event: full_strip_on
   3:
      event: first_led_green
```

Using the keys 1 and 2 I can switch on and off the entire light chain, so that is working good. Now I have added an action for key number 3, aim is when I press key 3 then ONLY one LED (here 0) should switch to green. mpf doesn't seem to like my addition to the light player section where I tried to address that single LED with 0-0-0. Can I pick a single LED from my chain if the chain is defined that way? I cannot imagine that I can only perform actions on all lights of the chain, typically I want to address single lights.

Any help is appreciated. Thanks.

**Comment by Leeoneil-Vely** [comment]
I'm not sure to understand everything, but i think first you need to declare all of your LED, one by one.
I'm not sure the light_stripe is ok when you want to work on a single LED.
But maybe i'm not right...

Example :
```
lights:
  led_0:
    start_channel: 0-0-0    # the exact number format depends on your platform
    subtype: led
    type: rgb    # will use red: 0-0, green: 0-1, blue: 0-2
    tags: gi
  led_1:
    previous: led_0    # the exact number format depends on your platform
    subtype: led
    type: rgb    # will use red: 0-0, green: 0-1, blue: 0-2
    tags: gi
  led_2:
    previous: led_1
    subtype: led
    type: rgb   # will use red: 0-3, green: 0-4, blue: 0-5
    tags: gi
  led_3:
    previous: led_2
    subtype: led
    type: rgb   # will use red: 0-7, green: 0-8, blue: 0-9
    tags: gi
etc....
```
With that you can call your led with **led_0** for example, instead of 0-0-0
You don't need to use the tag entry, it's just an example from my config.
