### DISCUSSION TITLE
tokens in slide_player

### DISCUSSION THREAD

**Discussion by Stefku** [missionpinball/missionpinball#59] [General]
Hi there

I created a slide that shows some info for a short time as overlay over the "normal" slide. With the help of _tokens_ I parametrised it to show different texts:

```
slide_player:
  # A temporary fullscreen slide on top of the base slide
  s_left_flipper_active:         # just for testing :)
    popping_overlay_slide:
      tokens:
        text_content: SKILLSHOT!
```

```
slides:
  popping_overlay_slide:
    expire: 2s
    widgets:
      - type: image
        image: phantomsee
        z: 0
      - type: text
        text: (text_content)
        z: 2
```

This works well. Interestingly, I cannot find any documentation for tokens in slide_player. Just a [sample config](https://docs.missionpinball.org/en/stable/examples/slide_player/index.html?highlight=tokens). Maybe its a left over from older versions or it's implementation is not finished?

Problem arises if I want to parametrise the image as well. With `image: (image_name)` and the corresponding token
```
slide_player:
  s_left_flipper_active:
    popping_overlay_slide:
      tokens:
        image_name: phantomsee
        text_content: SKILLSHOT!
```
I get an error message: Cannot add Image widget. Image '(image_name)' is not a valid image name.

I tried to debug it with python, but I couldn't find a place in mpf where the problem arises. And I don't know how to start mpf mc in debugging mode (See #58 ).

Any ideas?
