### DISCUSSION TITLE
Python bug? MPF bug? Differences Linux/Windows?

### DISCUSSION THREAD

**Discussion by Pucksnok** [missionpinball/missionpinball#61] [Q&A] [answered]
Hello.
I'm working on my Pokémon pinball machine and I have one issue.
I use carousel mode to choose a pokémon when game begins and I use animations on events to move the pokemons around as I want. It works great in my developer machine running Windows 11 and Python 3.9, on my Ubuntu machine the behavior is completely different, it's Ubuntu 20.04 so it runs Python 3.8.

I use the carousel mode example with the doctors and have replaced it with widgets and display it over the current slide. So far so good. The problem is when I use my move_right and move_left variables which now are set by left and right flipper button the behavior on the two machines are completely different.

When I use my variable_player to set var_choose_pokemon it seems like on the Windows machine with Python 3.9 the variable sets first then check the variable in my conditional animation. On my linux machine it seems to be the other way around. Posted videos on youtube for it.

My Windows machine: https://youtu.be/yGycoZTJWvw
My Ubuntu machine: https://youtu.be/AJBWdyLHMck

Example: If I have pokemon 1 choosen at start which set variable var_choose_pokemon==1 then I need to use "            move_left{current_player.var_choose_pokemon==6}: an_choose_pokemon_move_to_six" to do my animation to jump to the last pokemon.

Look at the video what happens on my linux machine, it's the exact same code, even double checked it just to be sure I didn't miss anything when transfering the files, I even went so far I deleted all files and moved over all files from the Windows machine.
Is this some bug? Something I do wrong or is it just a Python 3.8 or 3.9 difference?

```
mode_settings:
    selectable_items: Pokemon01, Pokemon02, Pokemon03, Pokemon04, Pokemon05, Pokemon06
    select_item_events: s_launch_button_active
    next_item_events: move_right
    previous_item_events: move_left

widget-stuff....:
        animations:
            move_right: an_choose_pokemon_move_one_step_right
            move_left: an_choose_pokemon_move_one_step_left
            move_left{current_player.var_choose_pokemon==6}: an_choose_pokemon_move_to_six
            move_right{current_player.var_choose_pokemon==1}: an_choose_pokemon_move_to_one 


event_player:
    carousel_Pokemon01_highlighted: select_Pokemon01
    carousel_Pokemon02_highlighted: select_Pokemon02
    carousel_Pokemon03_highlighted: select_Pokemon03
    carousel_Pokemon04_highlighted: select_Pokemon04
    carousel_Pokemon05_highlighted: select_Pokemon05
    carousel_Pokemon06_highlighted: select_Pokemon06

variable_player:
    carousel_Pokemon01_highlighted:
        var_choose_pokemon:
            int: 1
            action: set
    carousel_Pokemon02_highlighted:
        var_choose_pokemon:
            int: 2
            action: set
    carousel_Pokemon03_highlighted:
        var_choose_pokemon:
            int: 3
            action: set
    carousel_Pokemon04_highlighted:
        var_choose_pokemon:
            int: 4
            action: set
    carousel_Pokemon05_highlighted:
        var_choose_pokemon:
            int: 5
            action: set
    carousel_Pokemon06_highlighted:
        var_choose_pokemon:
            int: 6
            action: set
```

**Comment by Pucksnok** [comment]
Can add that the variables shows exactly the same in the console, the placeholder text in the bottom is changed with the widget_player and use the carousel_PokemonXX_highlighted: as a trigger, so that is correct on both OS.

**Comment by Pucksnok** [comment]
I have now tried python 3.8 on my windows machine and it still works as intended, no clue what's happening. 

If I use variable_player to set var_choose_pokemon on the event move_left and move_right, do this variable change before my animation trigger move_left and move_right happens? It seems to be so on the Windows machine but the Linux machine it seems to be the other way around with the exact same code.

```
#config_version=5
##! mode: choose_pokemon
# put this in your modes/carousel/config/carousel.yaml
mode:
    start_events: mode_base_started{current_player.ball==1}
    stop_events: carousel_item_selected
    code: mpf.modes.carousel.code.carousel.Carousel
    priority: 10000
    use_wait_queue: true
mode_settings:
    selectable_items: Pokemon01, Pokemon02, Pokemon03, Pokemon04, Pokemon05, Pokemon06
    select_item_events: s_launch_button_active
    next_item_events: move_right #s_left_flipper_inactive
    previous_item_events: move_left #s_right_flipper_inactive

widget_player:
    carousel_Pokemon01_highlighted{current_player.var_left_or_right==0}:
        select_Pokemon01:
            action: add
    carousel_Pokemon01_highlighted:
        select_Pokemon1:
            action: update
            key: poke_text_choose_pokemon
    carousel_Pokemon02_highlighted:
        select_Pokemon2:
            action: update
            key: poke_text_choose_pokemon
    carousel_Pokemon03_highlighted:
        select_Pokemon3:
            action: update
            key: poke_text_choose_pokemon
    carousel_Pokemon04_highlighted:
        select_Pokemon4:
            action: update
            key: poke_text_choose_pokemon
    carousel_Pokemon05_highlighted:
        select_Pokemon5:
            action: update
            key: poke_text_choose_pokemon
    carousel_Pokemon06_highlighted:
        select_Pokemon6:
            action: update
            key: poke_text_choose_pokemon                                                         



    


widgets:
    select_Pokemon01:
      - type: text
        text: PLAYER (number) - SELECT STARTER POKÉMON
        font_name: Impact
        font_size: 80
        color: white
        y: top-250
        x: center
        z: 10000
      - type: image
        image: up_arrow #569x569 pixels circle
        scale: 1
        x: center
        y: center-240
        z: 10000
      - type: image
        image: choose_pikachu #569x569 pixels circle
        scale: 0.8
        x: center
        y: center
        z: 10000
        animations:
            move_right: an_choose_pokemon_move_one_step_right
            move_left: an_choose_pokemon_move_one_step_left
#tried this, not making any difference....
            # move_right{current_player.var_choose_pokemon!=1}: an_choose_pokemon_move_one_step_right
            # move_left{current_player.var_choose_pokemon!=6}: an_choose_pokemon_move_one_step_left
            move_left{current_player.var_choose_pokemon==6}: an_choose_pokemon_move_to_six
            move_right{current_player.var_choose_pokemon==1}: an_choose_pokemon_move_to_one  
      - type: image
        image: choose_sirfetchd
        scale: 0.8
        x: center+580
        y: center
        z: 1000 
        animations:
            move_right: an_choose_pokemon_move_one_step_right
            move_left: an_choose_pokemon_move_one_step_left  
            move_left{current_player.var_choose_pokemon==6}: an_choose_pokemon_move_to_six
            move_right{current_player.var_choose_pokemon==1}: an_choose_pokemon_move_to_one  
      - type: image
        image: choose_lucario
        scale: 0.8
        x: center+1160
        y: center
        z: 1000
        animations:
            move_right: an_choose_pokemon_move_one_step_right
            move_left: an_choose_pokemon_move_one_step_left 
            move_left{current_player.var_choose_pokemon==6}: an_choose_pokemon_move_to_six
            move_right{current_player.var_choose_pokemon==1}: an_choose_pokemon_move_to_one 
      - type: image
        image: choose_dragonite
        scale: 0.8
        x: center+1740
        y: center
        z: 1000
        animations:
            move_right: an_choose_pokemon_move_one_step_right
            move_left: an_choose_pokemon_move_one_step_left  
            move_left{current_player.var_choose_pokemon==6}: an_choose_pokemon_move_to_six
            move_right{current_player.var_choose_pokemon==1}: an_choose_pokemon_move_to_one  
      - type: image
        image: choose_gengar
        scale: 0.8
        x: center+2320
        y: center
        z: 1000
        animations:
            move_right: an_choose_pokemon_move_one_step_right
            move_left: an_choose_pokemon_move_one_step_left  
            move_left{current_player.var_choose_pokemon==6}: an_choose_pokemon_move_to_six
            move_right{current_player.var_choose_pokemon==1}: an_choose_pokemon_move_to_one  
      - type: image
        image: choose_dragonite
        scale: 0.8
        x: center+2900
        y: center
        z: 1000
        animations:
            move_right: an_choose_pokemon_move_one_step_right
            move_left: an_choose_pokemon_move_one_step_left 
            move_left{current_player.var_choose_pokemon==6}: an_choose_pokemon_move_to_six
            move_right{current_player.var_choose_pokemon==1}: an_choose_pokemon_move_to_one  
            
#Pikachu, Darcovish, Sirfetch'd, Gengar, Lucario, and Dragonite
    select_Pokemon1:
      - type: text
        text: Pikachu - All electric shots 1.5x multiplier
        style: choose_pokemon_style_text

    select_Pokemon2:
      - type: text
        text: Sirfetch'd - All ballsaves and timed modes +7 seconds
        style: choose_pokemon_style_text

    select_Pokemon3:
      - type: text
        text: Lucario - 
        style: choose_pokemon_style_text

    select_Pokemon4:
      - type: text
        text: Darcovish - 1.5x bonus multiplier
        style: choose_pokemon_style_text

    select_Pokemon5:
      - type: text
        text: Gengar - All multitiballs gives one extra ball
        style: choose_pokemon_style_text

    select_Pokemon6:
      - type: text
        text: Dragonite - Fewer hits to beat trainers
        style: choose_pokemon_style_text


     
timers:
  carousel_timer:
    start_value: 4
    end_value: 0
    start_running: false
    direction: down
    tick_interval: 100ms
    control_events:
      - action: restart
        event: move_left
      - action: restart
        event: move_right

event_player:
    carousel_Pokemon01_highlighted: select_Pokemon01
    carousel_Pokemon02_highlighted: select_Pokemon02
    carousel_Pokemon03_highlighted: select_Pokemon03
    carousel_Pokemon04_highlighted: select_Pokemon04
    carousel_Pokemon05_highlighted: select_Pokemon05
    carousel_Pokemon06_highlighted: select_Pokemon06


    s_left_flipper_active{current_player.var_carousel_timer==0}: move_left
    s_right_flipper_active{current_player.var_carousel_timer==0}: move_right


variable_player:
    move_left:
        var_left_or_right:
            int: 1
            action: set
        var_carousel_timer:
            int: 1
            action: set
    move_right:
        var_left_or_right:
            int: 2
            action: set
        var_carousel_timer:
            int: 1
            action: set
    plunge_meter_start:
        var_left_or_right:
            int: 0
            action: set
    timer_carousel_timer_complete:
        var_carousel_timer:
            int: 0
            action: set

    carousel_Pokemon01_highlighted:
        var_choose_pokemon:
            int: 1
            action: set
    carousel_Pokemon02_highlighted:
        var_choose_pokemon:
            int: 2
            action: set
    carousel_Pokemon03_highlighted:
        var_choose_pokemon:
            int: 3
            action: set
    carousel_Pokemon04_highlighted:
        var_choose_pokemon:
            int: 4
            action: set
    carousel_Pokemon05_highlighted:
        var_choose_pokemon:
            int: 5
            action: set
    carousel_Pokemon06_highlighted:
        var_choose_pokemon:
            int: 6
            action: set
    carousel_Pokemon01_selected:
        var_collected_pikachu:
            int: 1
            action: set
    carousel_Pokemon02_selected:
        var_collected_sirfetchd:
            int: 1
            action: set
    carousel_Pokemon03_selected:
        var_collected_lucario:
            int: 1
            action: set
    carousel_Pokemon04_selected:
        var_collected_darcovish:
            int: 1
            action: set
    carousel_Pokemon05_selected:
        var_collected_gengar:
            int: 1
            action: set
    carousel_Pokemon06_selected:
        var_collected_dragonite:
            int: 1
            action: set

```

and my animations

```
    an_choose_pokemon_move_one_step_right:
        property: x
        value: -580
        relative: true
        duration: 0.3s
        easing: in_out_quad
    an_choose_pokemon_move_to_six:
      - property: x
        value: -2900
        relative: true
        duration: 0.3s
        easing: in_out_quad
    an_choose_pokemon_move_one_step_left:
      - property: x
        value: +580
        relative: true
        duration: 0.3s
        easing: in_out_quad
    an_choose_pokemon_move_to_one:
      - property: x
        value: +2900
        relative: true
        duration: 0.3s
        easing: in_out_quad
```
