### DISCUSSION TITLE
conditional event on light.color not working

### DISCUSSION THREAD

**Discussion by ohmbrew** [missionpinball/missionpinball#66] [Q&A]
Hello,

What is the syntax for conditional events checking for light color? According to the mpf spec, light color is monitorable via device.lights.[name].color.

I currently have the following. The SM transitions when shot_plunger_lane_exit_hit is fired without the conditional. But when I want to check if my 6th GI light is white, the state never changes. I've tried both ==white and =="white", neither work. Suggestions?

```
state_machines:
   skillshot_success:
     debug: true
     states:
       start:
         label: Skill shot ready
       success:
         label: Skill successful
         events_when_started: skill_success
       failed:
          label: Skill failed
          events_when_started: skill_failed
       transitions:
         - source: start
            target: success
            events: shot_plunger_lane_exit_hit{device.lights.gi_back6.color==white}
         #- source: start
          # target: failed
          # events: shot_plunger_lane_exit_hit{device.lights.gi_back6.color!=white}
```

I have a show that plays during skill shot:

```
shows:
  show_gi_back_chase:
    - duration: .5
      lights:
        gi_back1: white
        gi_back2: off
        gi_back3: off
        gi_back4: off
        gi_back5: off
        gi_back6: off
    - duration: .5
      lights:
        gi_back1: off
        gi_back2: white
        gi_back3: off
        gi_back4: off
        gi_back5: off
        gi_back6: off
    - duration: .5
      lights:
        gi_back1: off
        gi_back2: off
        gi_back3: white
        gi_back4: off
        gi_back5: off
        gi_back6: off
    - duration: .5
      lights:
        gi_back1: off
        gi_back2: off
        gi_back3: off
        gi_back4: white
        gi_back5: off
        gi_back6: off
    - duration: .5
      lights:
        gi_back1: off
        gi_back2: off
        gi_back3: off
        gi_back4: off
        gi_back5: white
        gi_back6: off
    - duration: 2
      lights:
        gi_back1: off
        gi_back2: off
        gi_back3: off
        gi_back4: off
        gi_back5: off
        gi_back6: white
```

Greg
