### DISCUSSION TITLE
(Solved) The best way to change mode

### DISCUSSION THREAD

**Discussion by Leeoneil-Vely** [missionpinball/missionpinball#69] [Q&A] [answered]
Hello everyone !
I'm trying to add a second mode on my game.
I have already a simple base mode, and I want to go to a second mode (mode2 for example), for example after hitting 5 time a switch.

I used the "counter:" script, and it's almost working.
No problem to activate the second mode, the mode2 si starting.
But i have 2 problems.
- When i lost the ball, the next ball start on base mode, not mode 2
and
- MPF crash randomly after the last ball drain (or if if hit the switch again)

What's the easiest way to change mode after hitting a switch multiple time, and is it possible to keep the mode active on the current player ?

Thank's for your help !

**Comment by Stefku** [comment]
One possibility is to track the state for the second mode for yourself with a player variable. Then, when a ball is starting you could decide if your second mode should start or not.

Here is an example, I made it out of my head and did some copy'n paste. I did not tested it.

base mode
```
player_vars:
   # save state of second mode
  second_mode_is_active:
    initial_value: 0

variable_player:
  activate_second_mode:
    second_mode_is_active: 1

event_player:
  # start second mode on event activate_second_mode. Fire it for example if your switch has been hit 5 times
  activate_second_mode:
    start_second_mode
  # start second mode if another ball started and the second mode was active at the last ball
  ball_started{current_player. second_mode_is_active == 1}:
    start_second_mode
```

second mode:
```
mode:
  start_events: start_second_mode
  stop_events: ball_will_end
```

PS: Maybe there is another way to track the state. But I don't know.

**Comment by atummons** [comment, marked as answer]
https://docs.missionpinball.org/en/stable/config/mode.html?highlight=Mode#restart-on-next-ball

Set restart_on_next_ball: true

If this mode is running when ball ends, it will automatically restart. If it's not running, it won't.

**Reply by Stefku** [reply]
cool, I didn't know that!

**Reply by Leeoneil-Vely** [reply]
edit : thank's it's working !!!! my crash problem is solved (see below)


I don' know if its working, because i can't have a second ball now... :/
I still have my crash issue when i lost the ball.
Draining is ok, but when the ball hit the plunger switch, mpf crash.
The error is strange
`Failed to load plugin 'c:\users\admin\appdata\local\programs\python\python38\share\gstreamer\bin\gioopenssl.dll'`
`Failed to load plugin 'c:\users\admin\appdata\local\programs\python\python38\share\gstreamer\bin\gstrtmp.dll': 'c:\users\admin\appdata\local\programs\python\python38\share\gstreamer\bin\gstrtmp.dll': Le module spécifié est introuvable.`
` Failed to load plugin 'c:\users\admin\appdata\local\programs\python\python38\share\gstreamer\bin\librtmp-1.dll': 'c:\users\admin\appdata\local\programs\python\python38\share\gstreamer\bin\librtmp-1.dll': Le module spécifié est introuvable.
Shutdown reason: BCP client local_display disconnected and exit_on_close is set`


edit : sometimes i'ts crashing the same way without hitting the second mode... So i have a larger problem with mode one i think....

I don't understand what i'm doing bad.
Can you "rapidly' check my 2 modes if you have some time ?
i'm trying several changes but nothing seems to work....

Base mode :

```
#config_version=5
mode:
  start_events: ball_started
  priority: 100

slide_player:
  mode_base_started:
    widgets:
      - type: text
        text: (score)
        number_grouping: true
        min_digits: 2
        font_size: 100
      - type: text
        text: PLAYER (number)
        y: 10
        x: 10
        font_size: 50
        anchor_x: left
        anchor_y: bottom
      - type: text
        text: BALL (ball)
        y: 10
        x: right-10
        anchor_x: right
        anchor_y: bottom
        font_size: 50

shots:
  base_bumper_one_shot:
    switch: s_popbumper_one
  base_bumper_two_shot:
    switch: s_popbumper_two
  base_bumper_three_shot:
    switch: s_popbumper_three
  base_sling_left_shot:
    switch: s_sling_left
  base_sling_right_shot:
    switch: s_sling_right
  base_scoop_bas_shot:
    switch: s_scoop_bas
  base_scoop_haut_shot:
    switch: s_scoop_haut



show_player:
  base_bumper_one_shot_hit:
    bumper1_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0
  base_bumper_two_shot_hit:
    bumper2_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0
  base_bumper_three_shot_hit:
    bumper3_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0
  base_sling_left_shot_hit:
    sling_left_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0
  base_sling_right_shot_hit:
    sling_right_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0


variable_player:
  base_sling_left_shot_hit:
    score: 100
  base_sling_right_shot_hit:
    score: 100
  base_bumper_one_shot_hit:
    score: 500
  base_bumper_two_shot_hit:
    score: 500
  base_bumper_three_shot_hit:
    score: 500
  base_scoop_bas_shot_hit:
    score: 1000
  base_scoop_haut_shot_hit:
    score: 2000


counters:
  cthulhu:
    count_events: base_scoop_bas_shot_hit
    starting_count: 0
    count_complete_value: 4
    events_when_complete: cthulhu_start


light_player:
  mode_base_started:
    gi:
      color: white

sound_player:
  mode_base_started:
    roaring_20:
      action: play
      loops: -1
  mode_base_stopped:
    roaring_20:
      action: stop
  base_bumper_one_shot_hit:
    punch:
      action: play
      volume: 1
  base_bumper_two_shot_hit:
    punch:
      action: play
      volume: 1
  base_bumper_three_shot_hit:
    punch:
      action: play
      volume: 1

sound_pools:
  roaring_20:
    load: preload
    type: random_force_all
    track: music
    sounds:
      - roaring_20
      - roaring_20_2
      - roaring_20_3
      - roaring_20_4
  punch:
    load: preload
    type: random
    track: sfx
    sounds:
      - punch1
      - punch2
      - punch3
      - punch4
      - punch5
      - punch6
      - punch7
      - punch8
      - punch9
      - punch10
```

Second mode :

```
#config_version=5
mode:
  start_events: cthulhu_start
  priority: 200
  restart_on_next_ball: true

widgets:
  cthulhu_start_banner:
    type: text
    text: CTHULHU STARTED
    font_size: 150
    color: lime
    y: 80%
    expire: 10s

widget_player:
  mode_cthulhu_started: cthulhu_start_banner

shots:
  cthulhu_bumper_one_shot:
    switch: s_popbumper_one
  cthulhu_bumper_two_shot:
    switch: s_popbumper_two
  cthulhu_bumper_three_shot:
    switch: s_popbumper_three
  cthulhu_sling_left_shot:
    switch: s_sling_left
  cthulhu_sling_right_shot:
    switch: s_sling_right
  cthulhu_scoop_bas_shot:
    switch: s_scoop_bas
  cthulhu_scoop_haut_shot:
    switch: s_scoop_haut



show_player:
  cthulhu_bumper_one_shot_hit:
    bumper1_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0
  cthulhu_bumper_two_shot_hit:
    bumper2_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0
  cthulhu_bumper_three_shot_hit:
    bumper3_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0
  cthulhu_sling_left_shot_hit:
    sling_left_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0
  cthulhu_sling_right_shot_hit:
    sling_right_light_show:
      action: play
      speed: 100
      priority: 200
      loops: 0


variable_player:
  cthulhu_sling_left_shot_hit:
    score: 1
  cthulhu_sling_right_shot_hit:
    score: 1
  cthulhu_bumper_one_shot_hit:
    score: 5
  cthulhu_bumper_two_shot_hit:
    score: 5
  cthulhu_bumper_three_shot_hit:
    score: 5
  cthulhu_scoop_bas_shot_hit:
    score: 1000
  cthulhu_scoop_haut_shot_hit:
    score: 2000


light_player:
  mode_cthulhu_started:
    gi:
      color: green

sound_player:
  mode_cthulhu_started:
    roaring_20:
      action: play
      loops: -1
  mode_cthulhu_stopped:
    roaring_20:
      action: stop
  base_cthulhu_one_shot_hit:
    punch:
      action: play
      volume: 1
  base_cthulhu_two_shot_hit:
    punch:
      action: play
      volume: 1
  base_cthulhu_three_shot_hit:
    punch:
      action: play
      volume: 1

sound_pools:
  roaring_20:
    load: preload
    type: random_force_all
    track: music
    sounds:
      - roaring_20
      - roaring_20_2
      - roaring_20_3
      - roaring_20_4
  punch:
    load: preload
    type: random
    track: sfx
    sounds:
      - punch1
      - punch2
      - punch3
      - punch4
      - punch5
      - punch6
      - punch7
      - punch8
      - punch9
      - punch10
```
