### DISCUSSION TITLE
Shot Group Show Only Works Second Time

### DISCUSSION THREAD

**Discussion by ttrickel** [missionpinball/missionpinball#88] [Q&A] [answered]
Sorry to trouble the community with what seems like it should be straight forward but I haven't been able to figure out what I'm missing.

When the reentry_shot completes for the first time the LEDs associated with the show just turn off after 2 seconds.

However, when the reentry_shot completes for the second time the LEDs associated with the show blink as expected.

What am I missing here?

```
#config_version=5
# reentry config file

mode:
  start_events: ball_started #reentry_start   #, device.shots.my_first_shot_mode2.state:0
  stop_events: ball_stopped #reentry_stop
  priority: 200

widgets:
  reentry_start_banner:
    type: text
    text: REENTRY STARTED
    font_size: 50
    color: lime
    y: 80%
    expire: 1s

widget_player:
  mode_reentry_started: reentry_start_banner

variable_player:
  reentry_shot_off_hit:
    score: 1000
  reentry_shot_lit_hit:
    score: 2000
  reentry_shot_lit_complete:
    score: 5000

shots:
  reentryL_shot:
    switch: s_reentry_left
    show_tokens:
      led: l_re-entry_left
    profile: reentry
 #   restart_events: mode_reentry_started

  reentryM_shot:
    switch: s_reentry_middle
    show_tokens:
      led: l_re-entry_middle
    profile: reentry
#    restart_events: mode_reentry_started
 
  reentryR_shot:
    switch: s_reentry_right
    show_tokens:
      led: l_re-entry_right
    profile: reentry
#    restart_events: mode_reentry_started
  
shot_groups:
    reentry_shot:
        shots: reentryL_shot, reentryM_shot, reentryR_shot
        rotate_left_events: s_left_flipper_active
        rotate_right_events: s_right_flipper_active
        reset_events: 
           reentry_shot_lit_complete: 2s # mode_reentry_started

shot_profiles:
  reentry:
    states:
      - name: off
        show: off
      - name: lit
        show: "reentry_lit"
    loop: true
#    block: true
        
show_player:
  reentry_shot_lit_complete:
    flash_yellow:
      loops: 0

shows: 
    flash_yellow:
        - duration: 2
          shows:
            flash_color:
              show_tokens:
                color: yellow
                leds: l_re-entry_left, l_re-entry_middle, l_re-entry_right
              speed: 4

    reentry_lit:    # can be done two ways
        - duration: -1      # this show step will run permanently
          lights:     # turn the light yellow
             (led): yellow
      #or this way
       #- lights:
       #       (led): yellow
```

**Comment by cobra18t** [comment, marked as answer]
What exactly do you want it to do?

You are resetting all the shots 2s after completing it with your reset_events:
```
shot_groups:
    reentry_shot:
        shots: reentryL_shot, reentryM_shot, reentryR_shot
        rotate_left_events: s_left_flipper_active
        rotate_right_events: s_right_flipper_active
        reset_events: 
           reentry_shot_lit_complete: 2s # mode_reentry_started
```

If your flash_color is not showing when you want, it may because the priority is too low. You are targeting the same LEDs with multiple simultaneous shows. If multiple shows have the same priority, the latest one wins. Maybe this gives you want you want?

```
flash_yellow:
        - duration: 2
          shows:
            flash_color:
              show_tokens:
                color: yellow
                leds: l_re-entry_left, l_re-entry_middle, l_re-entry_right
              speed: 4
              priority: 10
```
