### ISSUE TITLE
issue with lcd as DMD setup

### ISSUE THREAD

**Issue by borgdog** [missionpinball/missionpinball#123]
### Discussed in https://github.com/orgs/missionpinball/discussions/122

<div type='discussions-op-text'>

<sup>Originally posted by **borgdog** November 28, 2023</sup>
I'm setting up a lcd screen to have the DMD look at 192x64 size, following the instructions on this page [https://missionpinball.org/mc/displays/adding_dot_look_to_lcd/](url)

I was having trouble, so reduced my code down to just what that page shows but at the resolutions I want (plus stuff to actually run). It seems the part where it says "We do not set the number of dots in the DMD here, as that's automatically pulled in from the dmd display setting." is not working.  If I don't define the number of dots then it does 128 wide and whatever tall fits in the window.  Adding in dots_x and dots_y in the color_dmd slide with the appropriate values and everything works.

So, but in the code maybe? something changed where it doesn't work anymore?

my test config.yaml below, using latest dev (mpf 0.57.0.dev32, mpf-mc 0.57.0dev12)

`#config_version=6
# DMDTEST 

mpf:
    report_crashes: never

hardware:
  platform: smart_virtual

window:
  width: 1920
  height: 640

displays:
  window:
    width: 1920
    height: 640
  dmd:
    width: 192
    height: 64
    default: true
slides:
  window_slide:
    - type: display
      effects:
        - type: color_dmd
          dot_size: .65
          dots_x: 192
          dots_y: 64
      width: 1920
      height: 640
  dmd_slide:
    - type: text
      text: DOTS!
    - type: rectangle
      width: 192
      height: 64
      color: orange
      y: 0
      anchor_y: bottom
    - type: rectangle
      width: 192
      height: 64
      color: red
      y: top
      anchor_y: top
slide_player:
  init_done:
    window_slide:
      target: window
    dmd_slide:
      target: dmd`</div>

**Comment by borgdog** [comment]
I am going to add to this issue since it is all lcd as DMD related.

the next issue I'm coming across is trying to use fonts.  and following the example on this page: [https://missionpinball.org/mc/widgets/dmd_fonts/](url)

seems fairly straight forward, but what is now happening is if the text is centered  the font gets split and shows up like below.  left or right justified seem to work fine. 

![image](https://github.com/missionpinball/missionpinball/assets/26213296/0aca11f1-d8a5-4c14-9f11-23a833e05aa5)

Here is my test code that is producing that.

```
#config_version=6
# DMDTEST 

mpf:
    report_crashes: never

hardware:
  platform: smart_virtual

window:
  width: 1280
  height: 320
  resizable: false
  fullscreen: false
  borderless: true
  exit_on_escape: true

displays:
  window:
    width: 1280
    height: 320
  
  dmd:
    width: 128
    height: 32
    default: true
slides:
  window_slide:
    - type: display
      effects:
        - type: color_dmd
          dot_size: .5
      width: 1280
      height: 320
  dmd_slide:
    - type: text
      style: big
      text: MISSION
slide_player:
  init_done:
    window_slide:
      target: window
    dmd_slide:
      target: dmd
```

I'm not sure if it an artifact of how it is scaling, but that is really my next issue, it is also messing up images, and not scaling them true. I am making my images at 192x64 so I can control each dot color, but when it scales them it averages all them together, blurring the image and not giving true dot colors. here you can see the effect just on the fonts by adding dot_filter: false to the effects: part of the script  that font is a pixel style with nice square corners etc.

![image](https://github.com/missionpinball/missionpinball/assets/26213296/ab9838d0-7ed2-48c1-bf91-4ad860376b79)


again, I'm running this on the latest dev as listed in my first comment
